title: Hello my page blog
author: Artem @sledus
email: your-email@domain.com
description: > # В английском языке тысячи идиом, но точное число назвать невозможно, так же как нельзя назвать точное количество слов в языке. Например, в Кэмбриджском международном словаре идиом (Cambridge International Dictionary of Idioms, M. McCarthy, 1998) 5782 словарные статьи, но на самом деле это число мало о чем говорит.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
